# Generated by Django 2.1.5 on 2019-12-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveFileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('source_name', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='nr')),
                ('type', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='nr')),
                ('name', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='nr')),
                ('value', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='nr')),
            ],
            options={
                'verbose_name': 'save file',
                'verbose_name_plural': 'save files',
                'db_table': 'save_fail',
            },
        ),
    ]
